version: '1'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./database/data:/data/db
  DigitalNotes:
    image: webservice
    restart: always
    container_name: DigitalNotes
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      - "MONGO_HOSTNAME=mongodb"
